# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.provider "virtualbox" do |v|
  v.gui = true
end

config.vm.define "ubuntu" do |ubuntu|
   ubuntu.vm.box = "ubuntu/xenial64"
   ubuntu.vm.network "private_network", ip: "192.168.44.20", auto_config: false
   ubuntu.vm.hostname = "ubuntu"
   ubuntu.vm.synced_folder '.', '/vagrant', disabled: true
end

config.vm.define "centos" do |centos|
   centos.vm.box = "centos/7"
   centos.vm.network "private_network", ip: "192.168.44.21", auto_config: false
   centos.vm.hostname = "centos"
   centos.vm.synced_folder '.', '/vagrant', disabled: true
   centos.ssh.insert_key = false

end

config.vm.define "windows" do |windows|
   windows.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
   windows.vm.network "private_network", ip: "192.168.44.22", auto_config: false
   windows.vm.hostname = "w2k12"
   windows.vm.synced_folder '.', '/vagrant', disabled: true
end

config.vm.define "osx" do |osx|
   osx.vm.box = "carbon/osx-elcapitan-10.11"
   osx.vm.network "private_network", ip: "192.168.44.23", auto_config: false
   osx.vm.hostname = "osx"
   osx.vm.synced_folder '.', '/vagrant', disabled: true
end

end
